### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "test12345",
  "name": "Test",
  "phone": "01056821224",
  "role": "STORE_OWNER"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "test12345"
}


### 1. 로그인 요청 (JWT 발급)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "test12345"
}

> {%
    client.global.set("jwt_token", response.body.data.token)
%}

### 토큰 점검
GET http://localhost:8080/api/users/me
Authorization: Bearer {{jwt_token}}

### 2. 매장 생성 요청
POST http://localhost:8080/api/stores
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "홍길동의 빵집2",
  "address": "서울특별시 강남구 테헤란로 123",
  "phone": "02-123-4567",
  "description": "남은 빵을 특가 판매하는 매장입니다.",
  "openTime": "09:00",
  "closeTime": "21:00",
  "latitude": 37.12345,
  "longitude": 127.12345
}
